### ISSUE TITLE
Rename to OCA/privacy?

### ISSUE THREAD

**Issue by yajo** [OCA/data-protection#3]
I'm just wondering about this.

If we're gonna prefix privacy addons with `privacy_`, then it makes sense to rename the repo to `OCA/privacy`.

Maybe it's too much work for such a stupidity; well... just asking what you think. :innocent:

**Comment by dreispt** [comment]
Well, I did [propose](https://odoo-community.org/groups/gdpr-61/gdpr-77650?mode=thread&date_begin=&date_end=) it to be named `OCA/data-privacy`...

I think `data-privacy` is more expressive than just `privacy`.

**Comment by dreispt** [comment]
More opinions?

**Comment by yajo** [comment]
I'm starting to think that it's not worth the effort. It's done now, let's move on :wink:

**Comment by dreispt** [comment]
@Yajo, on the contrary - I see no objections.
And i don't think the change means too much effort.
