### ISSUE TITLE
[RFC] Allow to manage consent manually

### ISSUE THREAD

**Issue by rousseldenis** [OCA/data-protection#39]
@Yajo I discovered this repo and enjoyed.

I think consents should be managed also manually (if people don't want to use the mail feature, or for specific needs).

I will make a PR in that way allowing to use both modes (parameter on activity I think)

**Comment by rousseldenis** [comment]
https://github.com/OCA/data-protection/pull/40

**Comment by yajo** [comment]
Let me close this as we continue discussion in #40.
