### ISSUE TITLE
travis-ci.org still used here?

### ISSUE THREAD

**Issue by yajo** [OCA/data-protection#48]
Hi there. I just noticed 16b58ea2a6a591b1fb2051bbff8e5960fe6272c5 (branch 13.0) has [a run agains travis.org](https://travis-ci.org/github/OCA/data-protection/builds/749799710), which is supposed to disappear soon, isn't it? I guess something needs to be updated here... 🤔

**Comment by sbidoul** [comment]
@yajo I've not forced pushed the template to 13.0. There are couple of issues to fix first. And even then, I'm only doing it of `.copier-template.yml` is present. So closing this as there is nothing to do specifically here.

**Comment by pedrobaeza** [comment]
AFAIK, this has nothing to do with the template, but with the transfer from travis-ci.org to travis-ci.com, that you performed massively some time ago.

**Comment by sbidoul** [comment]
Aah, I see, sorry I misread the issue. It might be because this repo still had a travis-ci.org webhook configured? I just removed it.
