### ISSUE TITLE
Install error privacy module

### ISSUE THREAD

**Issue by asismorodo** [OCA/data-protection#52]
getting the following error when installing v.13 of the privacy module:

`
ValueError: <class 'odoo.tools.convert.ParseError'>: "Invalid field 'view_type' on model 'ir.actions.act_window'
<data>

    <record id="action_data_protection_partner_form" model="ir.actions.act_window">
        <field name="name">Partners</field>
        <field name="type">ir.actions.act_window</field>
        <field name="res_model">res.partner</field>
        <field name="view_type">form</field>
        <field name="view_mode">kanban,tree,form</field>
    </record>

    <menuitem id="parent_menu_data_protection" name="Privacy" groups="group_data_protection_user" web_icon="privacy,static/description/icon.png"/>

    <menuitem id="menu_data_protection_master_data" name="Master Data" parent="parent_menu_data_protection" groups="group_data_protection_user" sequence="10"/>
    <menuitem id="menu_data_protection_partner" name="Partners" parent="menu_data_protection_master_data" action="action_data_protection_partner_form" sequence="1010"/>
    <menuitem id="menu_data_protection_transaction" name="Transactions" parent="parent_menu_data_protection" groups="group_data_protection_user" sequence="20"/>
    <menuitem id="menu_data_protection_report" name="Reports" parent="parent_menu_data_protection" groups="group_data_protection_user" sequence="30"/>

    <record id="action_data_protection_config" model="ir.actions.act_window">
        <field name="name">Data Protection Settings</field>
        <field name="type">ir.actions.act_window</field>
        <field name="res_model">res.config.settings</field>
        <field name="view_mode">form</field>
        <field name="target">inline</field>
        <field name="context">{'module': 'data_protection'}</field>
    </record>
    <menuitem id="menu_data_protection_setting" name="Settings" parent="parent_menu_data_protection" action="action_data_protection_config" groups="group_data_protection_manager" sequence="90"/>

</data>
/opt/odoo/v13/github/oca/data-protection/privacy/views/data_protection_menu_view.xml
4" while evaluating
'records.button_immediate_install()'
`

**Comment by pedrobaeza** [comment]
Your local branch is not the correct.
